version: '3'
services:
  nlp_env:
    build: .
    ports:
    - "8888:8888"
    volumes: 
    # ホスト側に配置したファイルをコンテナ側と共有する
    - ./workspace:/opt/workspace
    # mecabの辞書ファイルの変更を永続化する
    - mecab_dictionary:/opt/mecab_setting

    # mecabの設定ファイルの永続化用volume
volumes: 
  mecab_dictionary: